//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.18 at 10:31:31 PM COT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://spring.soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spring.soap.producingwebservice.models;
